### ISSUE TITLE
Can't print

### ISSUE THREAD

**Issue by FraMecca** [tltx/MeC64#2]
Hi
You already know my interest in this project. I have noticed that in the stl that I have pulled in the repo there are some stems that are unprintable because they are above ground level.

Can you add an .stl file that display only one converter (I don't have the skills to do that by my self)?

**Comment by tltx** [comment]
It's hard for me to update the model as I have forgotten how to use SketchUp and only have an old version on a really slow computer but I have at least made a model with only one regular adapter in it now. I can't export to .stl though.

**Comment by FraMecca** [comment]
Ok, thanks. I'll export the stl then

**Comment by tltx** [comment]
Please push the .stl if was useful

**Comment by FraMecca** [comment]
Pushed the stl
